### ISSUE TITLE
fix course graph in dock mode

### ISSUE THREAD

**Issue by dvmarinoff** [dvmarinoff/Flux#113]
In dock mode choosing a course results in a home page graph thats way too long and off screen.

**Comment by TClin76** [comment]
![image](https://user-images.githubusercontent.com/96434118/162405461-e4916427-736e-4e34-9280-b9c5e5858e36.png)
It works well for selecting a course in dock mode on my computer  😄

**Comment by dvmarinoff** [comment]
Yes, thanks it's fixed now. Although the strange gap in the bottom row (right corner) in your screenshot is not supposed to be there. I can't replicate this, can you share on what OS, browser and screen size was this taken?

**Comment by TClin76** [comment]
I ed it in my office, and here I am using Win11 with a screen resolution of 1920x1080.
Browser is Chrome.

**Comment by TClin76** [comment]
Are you talking about the gap as red circle?
![image](https://user-images.githubusercontent.com/96434118/162914739-47efec83-c23d-48b7-8c46-e3a763bb8704.png)
That is because I drag the window to make it larger and then drag it back to normal size. 
After doing that, it comes out the gap.
