### ISSUE TITLE
SteadyState with PowerLow /PowerHigh Attribute

### ISSUE THREAD

**Issue by TClin76** [dvmarinoff/Flux#119]
![image](https://user-images.githubusercontent.com/96434118/166854675-d4a97190-6fdf-4165-b763-70ef54a29f33.png)
Hi @dvmarinoff 
I found that there are some zwo files downloaded from Whatsonzwift use PowerHigh and PowerLow within SteadyState Duration command.
FLUX does not recognize this kind of syntax but only accept PowerHigh and PowerLow within Warmup/Cooldown Duration.
In this case, FLUX shows power target =0 in this interval.

**Comment by dvmarinoff** [comment]
Having Low and High attributes on a SteadyState doesn't make any sense to me, but indeed it is working in this unexpected way:
![Screenshot 2022-05-05 at 9 10 28](https://user-images.githubusercontent.com/7523832/166870956-b2968fd2-f19f-4c92-a160-697388feadc6.png)

**Comment by dvmarinoff** [comment]
Just pushed a fix for this case to the development version.

My guess is that this situation arises from visual editors transforming SteadyState intervals to Ramps and back.
So if PowerLow and PowerHigh are present on a SteadyState the App will take the higher value from the 2 and use it as Power.

In this example workout all SteadyState will result in intervals of 60s at 0.70% of FTP:
```
    <workout>
        <SteadyState Duration="60" Power="0.70"/>
        <SteadyState Duration="60" PowerLow="0.70" PowerHigh="0.70" />
        <SteadyState Duration="60" PowerLow="0.40" PowerHigh="0.70" />
        <SteadyState Duration="60" PowerLow="0.70" PowerHigh="0.40" />
        <SteadyState Duration="60" Power="0.70" PowerLow="0.70" PowerHigh="0.70" />
    </workout>
```

![Screenshot 2022-05-05 at 12 26 35](https://user-images.githubusercontent.com/7523832/166897770-492b09b5-0dcc-4a8a-ba9b-5d4f033ca379.png)

**Comment by dvmarinoff** [comment]
@TClin76 Thanks for reporting the issue!

**Comment by TClin76** [comment]
> Just pushed a fix for this case to the development version.
> 
> My guess is that this situation arises from visual editors transforming SteadyState intervals to Ramps and back. So if PowerLow and PowerHigh are present on a SteadyState the App will take the higher value from the 2 and use it as Power.
> 
> In this example workout all SteadyState will result in intervals of 60s at 0.70% of FTP:
> 
> ```
>     <workout>
>         <SteadyState Duration="60" Power="0.70"/>
>         <SteadyState Duration="60" PowerLow="0.70" PowerHigh="0.70" />
>         <SteadyState Duration="60" PowerLow="0.40" PowerHigh="0.70" />
>         <SteadyState Duration="60" PowerLow="0.70" PowerHigh="0.40" />
>         <SteadyState Duration="60" Power="0.70" PowerLow="0.70" PowerHigh="0.70" />
>     </workout>
> ```
> 
> ![Screenshot 2022-05-05 at 12 26 35](https://user-images.githubusercontent.com/7523832/166897770-492b09b5-0dcc-4a8a-ba9b-5d4f033ca379.png)
> 
> Here are the test cases:
> 
> https://github.com/dvmarinoff/Flux/blob/85612444508da832ab021e76b465c8551ce1305c/test/workouts/zwo.test.js#L549

I modify the zwo file and let powerHigh and powerLow have different value, and then test it in Zwift.
The result will be the average of two values.

**Comment by dvmarinoff** [comment]
True that, just checked too it in Zwift! Will update the code.

<img width="246" alt="Screenshot 2022-05-05 at 13 38 49" src="https://user-images.githubusercontent.com/7523832/166907411-f3741d08-7643-4943-ac86-80253c8b66a0.png">

<img width="975" alt="Screenshot 2022-05-05 at 13 38 03" src="https://user-images.githubusercontent.com/7523832/166907427-d0a9e39d-3de8-4083-ac05-998c8786feb0.png">

**Comment by dvmarinoff** [comment]
Updated the code to take the avg value if powerLow and powerHigh differ:

![Screenshot 2022-05-05 at 13 57 01](https://user-images.githubusercontent.com/7523832/166909859-434f495f-2c42-4094-ae7f-45379f7f23f8.png)

**Comment by dvmarinoff** [comment]
Merged into master, closing this one.
