### ISSUE TITLE
Feature request: Support of automatic upload to Strava

### ISSUE THREAD

**Issue by KlausMu** [dvmarinoff/Flux#136]
Great project, exactly what I was looking for! So cool!
As far as I see, upload to Garmin connect is supported. Any chance to support the connection to Strava for having automatic upload of fit files?

**Comment by dvmarinoff** [comment]
Just working on integration with Intervals.icu, Strava will come maybe later.

**Comment by dvmarinoff** [comment]
The strava integration is ready and working, I am currently testing it for stability until the end of the week and publishing.
