### ISSUE TITLE
Add calories to FIT file

### ISSUE THREAD

**Issue by twinchell8** [dvmarinoff/Flux#147]
Wondering if calories can be added to the output FIT file.  I see weight, power, heart rate, time, all that jazz is already there, so I assume just need to do a simple calculation for calories.  Anyways, love the app and thanks!

**Comment by dvmarinoff** [comment]
Thanks! 

Calories can be calculated directly from Power. I can sure add them to the file. I'd have to change the code in a few places and do some testing.

**Comment by dvmarinoff** [comment]
Just added total calories to the .FIT file session message. Strava and Garmin Connect will be overwriting the value, they both use different calculations from one another. Apple Health was using the raw .FIT file and was not re-calculating kcal, so workouts synced to Apple Health were displayed with 0 kcal. So I decided to finally add the field and fix the issue for AH and others that do not re-calculate kcal.
