### ISSUE TITLE
Constant speed with drastic power differences?

### ISSUE THREAD

**Issue by twinchell8** [dvmarinoff/Flux#148]
I did a 4x10m workout today, and the speed the app was outputting was the exact same, even though the power varied dramatically.  Given a constant 0 slope, how is this possible?

![image](https://github.com/dvmarinoff/Flux/assets/20305293/364d7be0-a451-4beb-b900-67ce4d4b79a7)

**Comment by dvmarinoff** [comment]
Thanks for the report!

First lets verify your local settings. On the Settings Tab under Simulation if it says `Speed` the app is going to take the speed as reported by the trainer and in most cases this is going to be just flywheel speed which is dependent only on the gear combination and does not take in account power. If it is switched to `Power` the app will calculate speed based on the power reported from the current power source (trainer or power meter). In this case we want it to be set to `Power`.
