### ISSUE TITLE
Feature request : Broadcast Metrics to Apple Watch - watchOS 10

### ISSUE THREAD

**Issue by kard8** [dvmarinoff/Flux#150]
The flux app is working good with my generic FTMS bike trrainer. 
With iSO 10, Apple has introduced support for Cycling power from CPS BLE sensors.
No support has been given for FTMS bikes.

Can you create a way to broadcast the cycle metrics in real-time to the apple watch by using BLE CPS server?

**Comment by dvmarinoff** [comment]
Hi, and welcome to the project repo!

This project is using web-bluetooth, which as technology only implements bluetooth clients (central), and does not support the creation of bluetooth servers (peripherals). This feature request won't be possible.

I do have a half finished iOS implementation of Flux, and a project for the Apple Watch, but this year I've been busy with another indoor cycling project and simply don't have the time to finish those.
