### ISSUE TITLE
Flux loses bluetooth connection every 5 minutes

### ISSUE THREAD

**Issue by jbiswas** [dvmarinoff/Flux#159]
While using Flux it loses the bluetooth connection every 5 minutes or so. The only solution that I found is that I have to reload the page and reconnect all the devices: Suito-T, Cadence Sensor, HRM. When the disconnect happens the "Controllable" and "HRM" LEDs remain green, but the values are not updated.

I am running Google Chrome on an M1 Mac.

**Comment by dvmarinoff** [comment]
Hi and thanks for the report,
I have a very similar setup to yours, I mostly use Chrome on M1 Mac, and sometimes jump to Chrome on Ubuntu.
Did 2 rides in the Mac this week, without any problems. After your report I did another 30 min ride and everything works fine, no dropouts, and every time I unplug the trainer from the power socket it disconnects, and the green indicator goes to red like 2 seconds later. I am not sure what the issue could be here.

Trainer: Tacx Flux S
HRM: Polar H10
Google Chrome: Version 118.0.5993.70 (Official Build) (arm64),
M1 Mac: Sonoma Version 14.0
