### ISSUE TITLE
Wrong speed

### ISSUE THREAD

**Issue by Gregdimakis** [dvmarinoff/Flux#173]
Since Christmas, the app has started showing wrong speed when uploaded to Garmin connect. Also it tries to load a map on Garmin. I noticed that prior to this, the activity had shown as connected with edge 1030 plus, but now there is no connection.

**Comment by dvmarinoff** [comment]
@Gregdimakis Thanks for the report!
I did a huge update on the .FIT parser. I see that the speed is not getting converted from k/h to m/s:

<img width="1074" alt="Screenshot 2024-01-03 at 22 50 06" src="https://github.com/dvmarinoff/Flux/assets/7523832/cde697da-2a50-4808-bf96-6d203a81ec1a">

Will fix that issue tomorrow morning. Meanwhile sorry for the inconvenience!

**Comment by dvmarinoff** [comment]
@Gregdimakis just updated the app with some fixes. Speed should be working fine now. Also fixed a timestamp bug with the Laps.
