### ISSUE TITLE
Possible time zone issue

### ISSUE THREAD

**Issue by myxpt2** [dvmarinoff/Flux#176]
Hi, thanks for this app - really appreciate all the work that goes into it. Just a note that I saw there had been some minor interface changes yesterday, but the recorded time zone of the ride was off by 11 hours. I double checked the mobile device time settings. Activity time was recorded as starting at: 04:35, but the actual device record time was 15:35. Thanks.

**Comment by dvmarinoff** [comment]
Thanks for the report!
I am currently working on total overhaul of the .FIT parser. Just pushed a fix for this issue and tested with a ride. Should be working alright now.

**Comment by myxpt2** [comment]
Thanks @dvmarinoff! 🥇
