### ISSUE TITLE
Local web server

### ISSUE THREAD

**Issue by kurtnolf** [dvmarinoff/Flux#182]
Great project ! Is there a reason that this SPA cannot run locally ? I installed a local web server and I downloaded the source . The home page loads fine but I cannot go into the workout or other pages. Any specific requirements to be able to run this on a local webserver ?

**Comment by dvmarinoff** [comment]
The project should run locally, it has no external dependencies except for the dev tools (parcel), but you can easily circumvent those. Have you tried the following steps?

```
git clone https://github.com/dvmarinoff/Flux.git
cd Flux/
npm install
npm run start
```

In a supported browser open: `localhost:1234/`

**Comment by kurtnolf** [comment]
> The project should run locally, it has no external dependencies except for the dev tools (parcel), but you can easily circumvent those. Have you tried the following steps?
> 
> ```
> git clone https://github.com/dvmarinoff/Flux.git
> cd Flux/
> npm install
> npm run start
> ```
> 
> In a supported browser open: `localhost:1234/`

Thanks for the instructions. It works fine.
