### ISSUE TITLE
Auto-pause workout when pedaling stops

### ISSUE THREAD

**Issue by 6thSen** [dvmarinoff/Flux#193]
Hi, would it be possible to add the option of pausing the workout automatically when pedaling stops?

**Comment by dvmarinoff** [comment]
@6thSen,

I've added auto-pausing +  auto-resuming from auto pausing to the dev version. Currently the timeout for auto-pausing is 4s, and the power threshold for auto-resuming is 40 watts.

**Comment by dvmarinoff** [comment]
Updated this feature to optional. It can be switched on from the Settings tab.
