### ISSUE TITLE
Allow any orientation for PWA

### ISSUE THREAD

**Issue by opentree27** [dvmarinoff/Flux#199]
Hey, love the project. It's been my main use ever since getting a smart trainer.

I've been using it as PWA on my android for simplicity on my samsung tablet. I've seen that in the `manifest.webmanifest` orientation is hardcoded to portait ->`"orientation": "portrait"`. Can this be changed to `"any"`? It would make much more sense for people with larger displays. 

Thanks!

**Comment by dvmarinoff** [comment]
Hi and welcome to the repo!

Sure, will include the correction in the next update.

**Comment by dvmarinoff** [comment]
Just added this the dev version.
