### ISSUE TITLE
Button for skip not working 

### ISSUE THREAD

**Issue by srnanek** [dvmarinoff/Flux#203]
Hello, skip button not working I'm latest version but on 0.1.43 is working.

**Comment by dvmarinoff** [comment]
Just ran a couple of tests with 0.1.49 on Mac and Android with Chrome. Can't seem to reproduce the issue. Both Lap/Skip button and the L shortcut key work there. We are talking about the button with the Watch Timer icon, right?

<img src="https://github.com/user-attachments/assets/d39e324e-650f-4f2b-a45e-48a6bdafea8c" width="320">

**Comment by srnanek** [comment]
Yes the Wath timer icon. I had problem on Android 13 One UI 5.1 with app and also in Chrome browser. 
I used my own Workout but also a tested app default Workouts.

**Comment by dvmarinoff** [comment]
My device is on Android 10, One UI 2.5. Can you attach some logs from the console as a screenshot or text.

**Comment by srnanek** [comment]
I used it from debug window and now it works.
Srry and thnks for help
