### ISSUE TITLE
During "Ramp" required cadence doesn't appear next to actual cadence.

### ISSUE THREAD

**Issue by karlacio** [dvmarinoff/Flux#206]
When I'm doing an interval with a prescribed cadence it will appear on screen next to the actual cadence.

When the interval is a "Ramp" like:
`<Ramp Duration="900" PowerLow="0.65449995" PowerHigh="0.92449993" Cadence="65">`
on display I see only actual cadence an no required cadence.

Furthermore it would also be nice to have an audible alarm when you don't respect the indicated cadence.

**Comment by dvmarinoff** [comment]
The developer version now can read a single Cadence target from the WarmpUp and Ramp Intervals.
Note that in 0.1.49 in order to see the cadence Target you will need to tab a few times on the Cadence Field to cycle to the Cadence Target field.
