### ISSUE TITLE
Trouble initiating workouts

### ISSUE THREAD

**Issue by sandwichNP** [dvmarinoff/Flux#208]
Hello, new user here and I'm not sure if I'm in the right place.  I love the app, seems to work great when it works.  My problem is initiating new workouts in 0.1.49.  I can "load" the workout and I see the plan, but when I press "play" the timer starts but the trainer doesn't start ramping.  I have a good connection and can read power and also command it (ie manually tell it to hold xxx watts) but it won't run the actual workout.

I "downgraded" back to 0.1.43 and now when I press the circled "play" button, the workout starts and seems to ramp/follow intervals as appropriate.  In fact, the little stopwatch button brings me to the next segment and back as appropriate, which is awesome.  So my question is- am I dumb and missing something with 0.1.49, or is there a bug here?

Am on updated Chrome with an Elite Suito trainer.  Bluetooth all the things and it worked fine with zwift.

**Comment by sandwichNP** [comment]
Just to add here, it looks like 0.1.49 is working correctly on firefox and chrome on a different computer at work.  It must be limited to the computer I have at home, as when I press the "play" button here, the workout is initiated and the progress bar starts...progressing.

**Comment by dvmarinoff** [comment]
Hi @sandwichNP, and welcome to the repo!

Thanks for the report, will need some time to look into. I made 2 changes that might effect that in version 0.1.49.

1. I removed the Start Workout button (the play icon with the circle), so now there is only one play button which has the dual function to starts the recording of data and to start the workout.

2. I added auto pause and auto resume feature. When the trainer sends 0 watts power for about 4 seconds the workout will automatically pause, and when the User resumes pedalling and hits power higher than a certain threshold the recording start again.

Hypotesis 1:
Maybe there is a logical edge case which or a stale state from the previous version of the app, which prevents the workout from starting.

Hypotesis 2:
The trainer is sending consecutive 0 watts way too fast, maybe high transmission rate (10Hz, 4Hz), and this causes the workout to pause and it appears to just not start.

What you can try for now is to exclude 1, by going full cycle start -> pause -> stop -> reload the page a few times. This will get any stale state gone.

I'll look into it and get back to you later.

**Comment by sandwichNP** [comment]
Thank you for the quick response.  Just wanted to report back- I came home and tried again with a fresh restart and the issue repeated even after a CTRL+R reload.  So, I tried deleting cookies in chrome and reloaded the page- that worked and the workouts are now initiating with the play button as they should.

FWIW- this is without a trainer attached or connected at all, just starting the workout and watching the “progress bar” go and requested resistance increase over time.  So, I guess everything is working now!

**Comment by dvmarinoff** [comment]
In that case it is most likely the app getting stuck with old data. Just to made clear, you can also reset the state by going full cycle with the start -> pause -> stop buttons and then reloading the page.

The app stores only the current workout session in the browser, but it is made to survive in between reloads so that users don't loose data on unintentional page reloads. So the data is going to be marked ready for removal only after the current workout session gets stopped. And then the reload it discard the current session. 

Thanks for the reports! Let me know if you have any other issues.
