### ISSUE TITLE
make the app able to work completely offline

### ISSUE THREAD

**Issue by dvmarinoff** [dvmarinoff/Flux#21]

**Comment by jonathancolledge** [comment]
This looks great. Can it work at all offline, if so, do you think you could give me a few pointers please? I loaded index.html and the settings, etc are greyed out. Thanks.

**Comment by jonathancolledge** [comment]
Wow, I missed your first comment. Thanks for this. I'll check it out.

**Comment by dvmarinoff** [comment]
Hi, note that this feature is only available on the [Beta Archive](https://dvmarinoff.github.io/Flux/) version of the app that is version number 0.0.5.
The latest version which has much better support for ANT+ on Linux Desktop is at [Latest](https://flux-three.vercel.app/).
All feedback is welcome!
