### ISSUE TITLE
Pick a better name

### ISSUE THREAD

**Issue by dvmarinoff** [dvmarinoff/Flux#43]
Flux is the name of my trainer and was just a temp choice so I can start coding the app. But it is not a good name because it conflicts with way too many other projects that have the same name including popular frameworks for React and Julia.
The new name needs to be unique and googleable. Zwift is example for good name, Trainer Road not so much (hard to pronounce or make you remember it). I've looked at cycling words in French and English, historical names in my native language and others.
Tried a couple of online name generators, but couldn't find something I like.

I need to settle on a name so I can buy a domain and put the project on some real hosting.

**Comment by mjunkmyjunk** [comment]
How about webTrainer?

**Comment by dvmarinoff** [comment]
Nice, keep them coming!
But I do prefer going with a made up word like Zwift or something non english, so it naturally has it's own identity.

**Comment by mjunkmyjunk** [comment]
poursuivant

per the TdF of Tete De La Course and poursuivant

**Comment by mjunkmyjunk** [comment]
I found a possible solution for you.

[https://static.boredpanda.com/blog/wp-content/uploads/2020/10/technology-comics-system32-1-5f7c08e8c6778__880.jpg
](url)

**Comment by flame-n** [comment]
- Vitelor (from vite, quick)
- Veloverse?

Awesome work on the app so far! Just tested the demo and I love it! <3

**Comment by dvmarinoff** [comment]
@flame-n , Thanks, glad you liked the App!

**Comment by TClin76** [comment]
Daken

"D"imitar
M"a"rinov 
Bi“k”e 
Pow"e"r 
Trai"n"

**Comment by PhatWheZ** [comment]
OpenSpin

@dvmarinoff, im super happy i found this project. Didnt want to fork out to Zwift just yet, and this does exactly what i need from an indoor trainer aspect.

Got a race coming up that im keen to prepare for, need to setup a workout based on their datapoints
![image](https://user-images.githubusercontent.com/19488741/154024510-15373606-7599-4deb-af79-fc079f04d62b.png)

**Comment by GCuser99** [comment]
I really like "OpenSpin" as suggested above. Another similar - VirtualSpin...

**Comment by Zhwifty** [comment]
Veloverse is a good name,  suggests both a universe and also a versus, as in against rival apps.

Great app so far. 

Would love to see some customisation of the interface, such as ability to remove fields,I crease/decrease field sizes. Like you can do with a bike computer.

**Comment by afrandsen** [comment]
Just found your repo, very nice indeed. Thanks for the great work.

A danish suggestion from me: 'Træd' or 'Traed'. Translates to 'step' or 'push'.
Fx. 'Træd i pedalerne!' means 'Step on the pedals!'.

**Comment by dvmarinoff** [comment]
@afrandsen Thanks!

tread.app or something, sounds good.
