### ISSUE TITLE
Enable larger fonts (13" laptop)

### ISSUE THREAD

**Issue by shoffmeister** [dvmarinoff/Flux#56]
Enabling larger fonts for a 13" laptop screen (HiDpi) would be very nice for improved readability (at a distance).

As it is, right now (Windows 10, Microsoft Edge), with the browser in full-screen mode (F11), the text information is somewhat hard to read, IMHO.

Right now, the screen is also not overly full, either, lots blank space where information could be present.

**Comment by dvmarinoff** [comment]
noticed that I did broke the workout graph while adding some code to scale it for different screen sizes, it was resulting in 0% height when you change the workout. So applied a fix and extended it to dynamically adjust when the user is manually resizing the window.

This time the changes are on a separate domain for the branch: [responsive branch](https://flux-responsive.vercel.app/)

**Comment by dvmarinoff** [comment]
Improved the styles to use a modern CSS grid + relative units system (px -> rem -> em). This allows for a fluid layout that fills the whole page assuring that the important controls are not hidden below viewport height.

Also support for Landscape phones and Dock Mode is now possible.

Landscape phones (740px by 360px):

![localhost_1234_(Galaxy S9)](https://user-images.githubusercontent.com/7523832/140535211-9ff97d7f-5a51-4a33-ae17-dab6772c8a8a.png)

and Dock Mode (1600px by 150px):

![localhost_1234_(Dock Mode (M))](https://user-images.githubusercontent.com/7523832/140535353-81873540-89eb-4c7e-9ee6-188b79befaaa.png)

**Comment by dvmarinoff** [comment]
We have now much better support for a larger set of screen sizes and devices. Home page is good up to 27'' monitors, for the other 2 there is room for improvement, but their design especially Settings page is just a temp and very far from final.

Closing this for now. It's merged and you can now use the main version on [master](https://flux-three.vercel.app/).
